ONSdigital/dp-frontend-renderer

config/config.go

Update configuration for React app so that it looks for relative paths to the APIs.
Should probably be reviewed at the same time as the [other pull request](https://github.com/ONSdigital/dp-dd-frontend-controller/pull/8)
Locally the following requests should return 200s, with expected response from APIs:
- GET request to `localhost:20000/dd/api/datasets` should return all data discovery datasets.
- POST request to `localhost:20000/dd/api/jobs` should return an ID of a new job.
- GET request to `localhost:20000/dd/api/jobs/job/{id}` should return the status of the ID you got in the previous request.
Anyone but me, preferably @ian-kent

Update js configuration defaults to relative paths, not absolute paths

---

assets/templates/dataset-filter/preview-page.tmpl
assets/templates/datasetLandingPage/filterable.tmpl

Updated styling and formatting around the "other downloads" accordion to better match the ux (https://projects.invisionapp.com/share/CQCR545XV#/screens/265606838).
Check that the dropdown matches the ux on the dataset landing page and the preview page.
(Requires the same branch on sixteens repo).
Anyone.

Updated classes for landing and preview page downloads dropdown

---

config/config.go

use href instead of url when updating download button link

use href instead of url when updating download button link

---

Dockerfile
Dockerfile.concourse
dp-frontend-renderer.nomad

* Various improvements to the nomad plan:
* Configure the healthy threshold and deadline
* Enable auto rollback on failed deploy
* Increase the stagger time to allow enough time for scheduling
* Allow for splitting the nomad classes so that apps that don't need the content volume can float
* Add the restart stanza to the nomad plan to support nomad 0.8 for new production.
* Update base docker image to use our Ubuntu image with ca-certificates bundled.
Ensure only nomad plan and docker image changes are included.
Anyone but me.

Release 1.2.1

---

assets/templates/datasetLandingPage/static.tmpl
main.go
render/helpers.go
render/helpers_test.go

Concatenating strings inside an `<a Href=""/>` attribute tag causes the string to be HTML escaped. Our preference is for our links not to be escaped to maintain human readability.
I've created a new render helper func for building the legacy dataset download links and used that in place of the current concatenation approach.
Also moved help funcs into separate package and added some unit tests for new func.
Running the CMD stack go to a legacy dataset landing page and download the latest version of a file - you should get the file and the download URI should not be escaped.

added new render helper func to create legacy dataset download links

---

assets/templates.go
assets/templates/datasetLandingPage/filterable.tmpl

Typography broke CMD styling.
Why? - CMD filterable template is using markdown styling.
Items which were broken and should now be fixed with this PR are:
* Headings are tabbed in
* Subheadings top padding removed
* List styling no longer appearing 'oddly' tabbed
1. Checkout this branch and the following for dp-fronted-renderer PR/Branch: https://github.com/ONSdigital/sixteens/pull/149
2. Run the CMD tech stack
3. Check that CMD content pages look as they should
4. Run the standard tech stack
5. Check that Articles (+Neutral), Compendiums and Bulletins still follow the new typography rules
Anyone on the developer team, ideally Frontend Dev except me.

CMD filterable template styling updated with new Typography

---

assets/templates.go
assets/templates/partials/release-alert.tmpl
vendor/github.com/ONSdigital/dp-frontend-models/model/datasetLandingPageFilterable/model.go
vendor/vendor.json

Fix for banner appearing on dataset landing pages:
- Goes to the web page rather than the API when you click ‘previous’
- Clicking previous now goes to the correct version (not the latest version of published that uses the dataset (different edition)
- Correctly shows previous and latest version banner (was previously showing ‘this is not the latest’ when it was if there was a version of a different edition of that dataset published.
Dependencies:
dp-frontend-dataset-controller: https://github.com/ONSdigital/dp-frontend-dataset-controller/pull/116
dp-frontend-models: https://github.com/ONSdigital/dp-frontend-models/pull/39
1. Get a dataset, make an edition, make a version of the edition
2. Get the same dataset and the same edition, make a new version
3. Get the same dataset, make a new …

Release alert showing previous and next now using a new flag

---

assets/templates.go
assets/templates/datasetLandingPage/static.tmpl

Added previous versions to legacy dataset pages rendered via the frontend-renderer, rather than babbage.
Go to a page like: /economy/inflationandpriceindices/datasets/consumerpriceindices on the ONS website. Note how there are previous versions shows. Now go to the same page but on the beta website. Note this is not shown. This PR should make the previous versions link show if there are previous versions, checkout the branch and confirm this is indeed happening with no side effects

Timeseries legacy datasets now show previous versions of a dataset

---

Dockerfile
Dockerfile.concourse
assets/templates.go
ci/scripts/build.sh

Although the localisation implementation was working locally. On environments, it uses a docker image and wasn't copying the localisation files across to be used as such it failed to deploy (unhealthy on startup).
Change `lang` cookie locally to 'cy' and run the docker image locally. Go to a legacy dataset page, ensure Welsh labels are being shown e.g. Home, search is in Welsh.

Fix, docker image to include locale file assets

---

ci/build.yml
ci/unit.yml

Bump Go version to 1.13.8 
Check that all required files are updated to 1.13.8
Anyone but me

bump go version to 1.13.8 in CI

---

assets/templates/cookies-preferences.tmpl
assets/templates/datasetLandingPage/static.tmpl
assets/templates/partials/cookies-banner.tmpl
assets/templates/partials/footer.tmpl

The legacy dataset landing pages were not loading due to an error in our templates regarding the way we reference the `Other` key from our localisation files. 
The reason this error wasn't being replicated on different pages that are served by the renderer (/cookies and CMD pages) is because the `Language` property for those pages is empty, thus meaning our `Localise` function defaults to `en` and thus uses the English localisation file. For the legacy dataset landing page, however, the `Language` property was set as `cy` and so is using the Welsh file.
The actual error was regarding the number we use to reference `Other` from within the `Localise` functions called in our templates - such as the Cookies banner and our footer. These keys are based on the [Unicode Common Locale Data …

Fix for localisation plurals

---

assets/templates/partials/footer.tmpl
config/config.go

The Open Government License (OGL) logo has been updated to match with the new footer typography. We now use an SVG and it is filled with `grey4` - `e2e2e3`
Check that the new OGL logo is present in the footer
Anyone but me

updated footer to use new OGL logo

---

assets/locales/active.cy.toml
assets/locales/active.en.toml
assets/templates/homepage.tmpl
assets/templates/homepage/around-the-ons.tmpl
assets/templates/homepage/in-focus.tmpl

This PR fixes a few bugs on the homepage:
- Promotional banners in Safari were misaligned with the population tile - the promos were pushed down slightly. This seemed to be caused by superfluous markup that Safari was still parsing, and Firefox/Chrome etc. weren't. The markup has subsequently been removed
- Fixed the titles "In Focus" -> "In focus"; "Around The ONS" -> "Around the ONS" and the copy for "Weekly Deaths" section
- Removed `underline-link` from each of the highlighted content section headings. This ensures that, on `:focus` states, the underline is not present - as per intended design
Ensure changes align with description above and that code changes are logical
Anyone but me

Homepage alignment/copy/focus state fixes

---

assets/templates/homepage/latest-releases.tmpl
config/config.go

- Added a modifier class `tile--latest-releases` to the latest releases tile. This ensures that the latest releases has a fixed height which ensures it aligns with the bottom of the Census promo banner in md/lg viewport sizes.
- Class name matches
- Check that the latest releases tile aligns with the bottom of the promo banners
Anyone but me

add modifier class to set latest releases to a fixed height

---

assets/templates/homepage/latest-releases.tmpl

Removed the ellipsis css class as that is no longer used owing to truncation happening in the Renderer.
Check that `tile__list-item-title` class is removed
Anyone but me

removed class that generates css ellipsis

---

assets/templates/main.tmpl
assets/templates/partials/banners/cookies.tmpl
config/config.go

This PR adds  a script tag which appends a `js` class to the body tag (i.e., to signify that JavaScript is enabled). This will allow us to implement certain JS-specific interactivity. In this case, it fixes a jitter bug we had with the cookies banner rendering on refresh.
Check the code changes make sense. Should include updated sixteens path, a change to add the script in the main template file, and another to add `cookies-banner--hidden` class which is where the functionality is implemented
Anyone but me

implemented cookies-banner--hidden class to fix jitter bug issue

---

assets/templates/homepage/main-figures.tmpl
config/config.go

- Increased `md` viewport col size for the Employment figures from `md--12` to `md--15`. This ensures the text wraps a bit closer to the edges of the tile width and subsequently decreases the height of the stacked employment tiles. This in turn means the Population tile is a bit shorter, ultimately ensuring a bit less whitespace is present in that tile
- Removed unneeded `col-md--12` classes from the Employment tile in the `large` viewport markup
- Decreased heights of other main figures tiles to ensure that they still lined up flush with the relevant parts of the Employment tile
**Before**
**After**
- Run this branch alongside `fix/employment-stacked-height` in Sixteens to see the changes locally
- Ensure code changes make sense
- This has been tested across browsers and viewport sizes, …

Change employment tile col size in md viewport

---

assets/templates/homepage/main-figures.tmpl

This PR sets an explicit height for desktop view of the homepage employment figures descriptions. This is because of the change from displaying a monthly figure to the annual figure instead, which changed the number of lines between the two and caused a discrepancy in the alignment
Ties into this [homepage controller PR](https://github.com/ONSdigital/dp-frontend-homepage-controller/pull/31)
**Without setting a height to the text**
**With setting explicit height to the text**
- Ensure that the change makes sense
Anyone

Set fixed height for employment/unemployment data descriptions

---

assets/templates/datasetLandingPage/static.tmpl

Changed the image alt text where the official statistic image is shown for the frontend-renderer this is just the dataset landing page.
1. Visit a dataset landing page
1. The alt text of the image will be not very descriptive - "National Statistics logo"
1. Check out this branch
1. See that the alt text of the image will now be "This is an accredited national statistic. For information about types of official statistics click this link."
Anyone

Non descriptive image alt for official statistic image on dataset landing page

---

assets/locales/active.cy.toml
assets/locales/active.en.toml
assets/templates/partials/header.tmpl

- Updated localisation files and subsequent alt text for the ONS logo in the header to now provide more context to where the link will lead to
Check that additional context in ONS logo alt is clear and is read correctly by the screen reader
Anyone but me

Update logo alt text in header component

---

assets/templates/datasetLandingPage/filterable.tmpl

Stop using `li` on dataset landing page when not in a list.
1. Load a data set landing page and see it looks as it does.
1. Loads this page.
1. See that the page is unchanged apart from the font sizes in the tiles on the right side being increased to 16 as per the contact per detailss
Anyone

Fix - Incorrect use of list on dataset landing page

---

assets/templates/feedback.tmpl

Fix labelling of inputs on service feedback form on CMD page
1. Click the feedback link  in the BETA header `This is a new way of getting data - your feedback will help us to improve it.`
1. See that the purpose, name, email and feedback fields are unlabelled.
1. Switch to this PR and see that is resolved.
Anyone but me

Fix unlabelled inputs on service feedback form

---

assets/templates/dataset-filter/filter-overview.tmpl
config/config.go

Updated the HTML in the `filter-overview` partial to be valid syntax by nesting an `li` underneath the `ul` instead of a `span`.
This change also lead to some of the styles changing too. As such, there is also a [PR in Sixteens](https://github.com/ONSdigital/sixteens/pull/204) which adds a utility class, `list--no-pipe`, which forcibly removes the `:after` content on any specific list item 
- [Pull latest Sixteens change from this branch](https://github.com/ONSdigital/sixteens/pull/204)
- Go to a filter page options page (you will need the Filter journey running). 
- Check that there is no material difference to the UI, but that the HTML is now valid
Anyone but me

Update list html validity

---

assets/locales/active.cy.toml
assets/locales/active.en.toml
assets/templates/partials/header.tmpl

This PR adds Welsh translation for the text, "Office for National Statistics logo - Homepage" that is applied to the ONS logo `alt` in the header. As the sentence structure differed between English and Welsh translations, it felt sensible to include the whole sentence as a separate key in the localisation files
Check that the alt text for the ONS logo in the header is correctly applied as per text in the localisation files on a page handled by the frontend renderer (e.g. the new homepage or a CMD journey page).
You can change the language locally by setting the cookie, `lang`, to either `en` or `cy`. Once the page is refreshed, the site should be in the language chosen
Anyone but me

added Welsh translation for ONS logo alt text

---

assets/templates/datasetLandingPage/static.tmpl

Changed the official statistics image alt text so it is less than 99 characters which is the limit read by some screen readers.
1. Visit a dataset landing page
1. The alt text of the image will be very long - "This is an accredited national statistic. For information about types of official statistics click this link."
1. Check out this branch
1. See that the alt text of the image will now be "This is an accredited National Statistic. Click for information about types of official statistics."
Anyone

Fix - Official statistics wording on dataset landing page

---

assets/templates/dataset-filter/filter-overview.tmpl

The button for applying filters in CMD was visually disabled but clickable. When clicked it would show any errors that you had. After discussions with UX this visual disabling has been removed and the use of `role="alert"` and `aria-live="assertive"` on the error div means the errors are read by the screen reader. 
This visual disabling was done in JS as well so you will also need to checkout sixteens [fix/accessibility-disabled-but-clickable](https://github.com/ONSdigital/sixteens/tree/fix/accessibility-disabled-but-clickable)
Also, fix issue where button title was not being read by using `aria-label`.
1. View the CMD filter page
1. See that the apply filter button is visually disabled but clickable
1. See that the errors are not announced to the screen reader when clicked.
1. Switch to …

Fix - Accessible CMD filter errors

---

assets/templates/partials/header.tmpl
config/config.go

Added the aria-expanded attribute to the menu and search toggles in the mobile nav.
1 - Emulate/use a mobile device.
2 - Navigate to the homepage.
3 - Inspect the HTML for the Menu toggle
4 - There should be an aria-expanded=false attribute present.
5 - Inspect the HTML for the Search toggle
6 - There should be an aria-expanded=false attribute present.
(The functionality to toggle the value is included in a PR in the sixteens repo)

add aria expanded attribute to the mobile menu toggles

---

assets/templates/dataset-filter/age.tmpl
assets/templates/dataset-filter/geography.tmpl
assets/templates/dataset-filter/hierarchy.tmpl
assets/templates/dataset-filter/list-selector.tmpl
assets/templates/dataset-filter/time.tmpl
assets/templates/datasetLandingPage/filterable.tmpl
assets/templates/datasetLandingPage/version-list.tmpl
config/config.go

The details do not need these additional aria attributes as they are well supported and polyfill adds the necessary attributes when needed (for IE11)
1. Open a page with a `<details>` e.g. a CMD dataset filter with a description
1. See that the details expand and collapse but is confusing with a screen reader
1. Switch to this branch and `sixteens` `fix/accessibility-details-polyfill-not-needed`
1. See that details are more straight forward from a screen reader and still work 
Anyone but me

Fix - Stop adding aria attributes to details elements

---

assets/templates/main.tmpl

When landing on a 404 page the page title contains just the standard ending but no specifics to the page. This resolves it by using the error title when it has one
1. Go to a bad url e.g. http://localhost:20000/apfhoafhaohf
1. See that the page title is blank
1. Switch to this branch and restart
1. Refresh the page
1. See that title is now the error title followed by the standard ending
Anyone but me

Fix - Set correct page title for 404 pages

---

assets/templates/partials/header.tmpl

Set link to correct language so that it is read by screen reader correctly
1. Load any page rendered by this (e.g. home page, error page or CMD page)
1. Hear that `Cymraeg` is not read correctly (something like _sim-rig_)
1. Switch to this branch and hear it read correctly
1. Load any page rendered by this (e.g. home page, error page or CMD page)
1. See that the link to `cy.ons.gov.uk` has no `lang` attribute
1. Switch to this branch and see that it has a `lang` attribute of `cy`
Anyone but me

Fix - Language of language switch link

---

assets/templates/partials/banners/covid.tmpl

Change the link colour for the covid banner to increase contrast
1. Load the new home page
1. See that the link in the banner does not stand out against the yellow background
1. Switch to this branch and sixteens branch `fix/covid-text-contrast`
1. See that it is now improved and using colour `#003c57`
Anyone but me

Fix - Covid banner contrast

---

assets/templates/partials/footer.tmpl

Remove DOM that is added by JS and then used by the JS.
https://github.com/ONSdigital/sixteens/blob/3e13124b9a9a2f0de4a41f995ecb44f9e1f72ee7/js/app/viewport-size.js#L2
1. Load a page rendered by the renderer e.g. the home page
1. See that the `footer` has duplicated `div`s  with ids of `viewport-sm`, `viewport-md` and `viewport-lg`
1. See that the `footer` only has one of each `div`
Anyone but me

Fix - Remove duplicated nodes

---

assets/locales/active.cy.toml
assets/locales/active.en.toml
assets/templates/main.tmpl

Add meta description for homepage in the renderer to ensure Welsh translation viability. This means there is now additional logic to determine whether or nor the page being served is the homepage or not
Check code change makes sense and that the change is applied (i.e., a CMD dataset page's description still renders correctly and that the homepage description is rendered too)
Anyone but me

Add description logic for homepage

---

assets/templates/partials/json-ld/homepage.tmpl

Fixed JSONLD in homepage - `description` comes from the localisation tag rather than the page model
Ensure JSONLD control is enabled in the renderer - `ENABLE_JSONLD_CONTROL=true` and check that the homepage description in the JSONLD script is visible and matches the localisation text
Anyone but me

fix JSONLD homepage description to use localisation instead of model

---

assets/templates/homepage/around-the-ons.tmpl
assets/templates/homepage/in-focus.tmpl
assets/templates/partials/banners/survey.tmpl

Add alt text to the images on the home page
1. Visit the new home page
1. See that the `Taking part in a survey` checkbox, `In focus` images and `Around the ONS` images have no `alt` text
1. Switch to this branch and restart the renderer
1. See that the images now have reasonable alt text.
Anyone but me

Fix - Homepage - Image alt

---

assets/templates/dataset-filter/preview-page.tmpl
assets/templates/datasetLandingPage/static.tmpl
config/config.go

Improve text read by screen readers for download as links
1. Dataset landing pages
1. CMD filter download pages
1. Visit a page
1. Hear the screen reader read `.xls` etc
1. Switch to this branch and reload the page
1. Hear the screen reader read `Download {{title}} as {{format}}`
Anyone but me

Fix - Download as links

---

assets/templates/dataset-filter/preview-page.tmpl

Updated downloads options button on preview page to match dataset landing page, giving the button a correct focus state.
- navigate to a filtered dataset preview page
- set focus to the 'Other Downloads Options' button
- the button should have an orange surround to indicate focus.
Anyone but me.

change classes to match other download options button

---

assets/templates/homepage/around-the-ons.tmpl
assets/templates/homepage/in-focus.tmpl

The around ons image's alt text added no value and the in focus images will be set from florence later
1. Load the home page and see that the `In focus` and `Around the ONS` images have alt text
1. Load this branch
1. See that the alt text is empty
Anyone but me

Remove alt text for homepage images

---

assets/templates/homepage/around-the-ons.tmpl
assets/templates/homepage/in-focus.tmpl
assets/templates/partials/banners/cookies.tmpl
assets/templates/partials/banners/covid.tmpl
assets/templates/partials/footer.tmpl

Add sections around different areas of homepage so we can have multiple semantically correct h1 headings
1. Cookie banner
1. Covid banner
1. In focus
1. Around the ONS
1. Footer
1. Load the home page
1. See that the above areas have no h1
1. See the design is unchanged but are now using h1
Anyone but me

Fix - Homepage semantic headings

---

assets/templates/partials/filter-selection.tmpl

Announce to screen readers that there has been a change 
This has been tested with VoiceOver for Mac and NVDA. This component does not exist on mobile so no need to worry about VoiceOver for iPhone.
1. Visit a CMD filter page
1. Add a filter with a screen reader enabled
1. Hear the filter is not announced
1. Add the filter and hear that it announces the number of filters
Anyone but me

Fix - Announce when items added and removed from filters

---

assets/templates/dataset-filter/preview-page.tmpl
config/config.go

Removed the default aria-hidden from the excel-file element, instead it will be dynamically set by JS if required (update in sixteens PR https://github.com/ONSdigital/sixteens/pull/217)
Needs the references to sixteens updating once that PR has been merged.
- Apply filters to a dataset to create a custom download.
- Land on the download preview page with the file already available for download, the HTML element id='excel-file' should not have the attribute aria-hidden set
Anyone but me

remove aria-hidden from the excel file tag

---

assets/templates/dataset-filter/hierarchy.tmpl

Added an `aria-label` attribute so that the dimension name (`Label`) to proffer additional context for screen reader users.
Where screen readers would initially read, e.g., "browse 5 areas", it will now read: "Wales: browse 5 areas".
Pull branch and go to a filter dataset page. While the ticket specifically mentioned geography, this issue is something that was happening across the board. You could then test this change on a dataset with any dimensions that let you browse additional things (CPIH => Aggregate, for instance)
Ensure additional context read out by screen reader is clear
Anyone

Fix - Additional context for screen readers with browse button

---

assets/templates/dataset-filter/preview-page.tmpl
config/config.go

Fix the server side rendered aria-label on the CMD download page
1. Get to the CMD download page and wait for the download buttons to appear.
1. Refresh the page
1. See that the download buttons are missing the file size from their `aria-label`.
1. See that the download button contents is not read correctly on VO for iPhone
1. Switch to this branch 
1. See that the above issues are resolved
Anyone but me

Fix - Missing file size from aria-label

---

assets/templates/search.tmpl
assets/templates/search/bar.tmpl
assets/templates/search/results.tmpl

- Add search bar which contains an input box to enter a query and submit button
- Add search results container to list search responses based on the query
- Check if the code makes sense
- Can test locally by running web instances, `dp-search-query`, `dp-frontend-search-controller` and then on the browser, go to `http://localhost:20000/search`
- Search for `housing` for example and the search results will be updated
Please note that updates to `dp-frontend-search-controller` is still in PR (https://github.com/ONSdigital/dp-frontend-search-controller/pull/2), therefore you may need to pull my commits locally and test from there. This PR description box will be updated once it has been merged …

add templates for search page

---

assets/locales/active.cy.toml
assets/locales/active.en.toml
assets/templates/partials/header.tmpl
config/config.go

Screen readers (particularly on mobile) were picking up the '+' as a separate link. Added a slightly hacky patch to improve this until the new nav is implemented
(Main focus is on iPhone voiceover)
(Requires the PR from sixteens to work correctly https://github.com/ONSdigital/sixteens/pull/222)
- Using a screen reader on a mobile device.
- Go to any page and open the menu.
- Navigate to the first expansion toggle in the menu.
- You should not be able to navigate to the '+'.
- The screen reader should announce the name of the sub menu followed by 'sub menu toggle' and that it is collapsed.
- Expand the sub menu and the screen reader should announce the sub menu is now expanded.
- Navigate to the first item in the sub menu, the screen reader should announce the title of the menu item only. …

add slightly hacky patch to make the menu easier to  navigate on mobiles

---

assets/templates/search/results.tmpl

- Increase font-size in `meta`, `summary` and `keywords` of search results 
- Add an underline to the `title` of the search result
- Check if the code makes sense
- Run the web instances (which includes this `dp-frontend-renderer`) with `dp-frontend-search-controller` and `dp-search-query`, then on the browser, enter `http://localhost:20000/search?q=housing` to see the changes.
- Remember to enable the flag `SearchRoutesEnabled` to `true` in the `dp-frontend-router`
**Describe who worked on the changes, so that other people can review.**
Anyone - Justin made the changes

increase font-size and add underline in search results

---

assets/templates/dataset-filter/preview-page.tmpl
assets/templates/datasetLandingPage/filterable.tmpl
config/config.go

Fix CMD download options text overflow by removing text fixed width which does not work at such a small viewport width.
1. Visit a CMD dataset page and CMD filtered results page
1. Expand the "Other download options" set the viewport width to 320px
1. See that some of the options overflow
1. Switch to this branch and sixteens branch `fix/reflow-filterered-dataset-download`
1. See that the issues is fixed.
Anyone but me

Fix - Reflow - Text overflow in CMD download options

---

assets/templates/partials/header.tmpl
config/config.go

When expanding a collapsed menu item in the mobile menu then the language option overflows the menu and ends with nearly white text on white background.
1. Visit any page (a babbage or renderer)
1. Expand the menu
1. Expand a collapsed menu item
1. See that language link (at the bottom) has overflowed the menu
1. Switch to branches
1. Sixteens - `fix/mobile-nav-lang-overflow`
1. dp-frontend-render- `fix/mobile-nav-lang-overflow`
1. babbage - `fix/mobile-nav-lang-overflow`
1. See that it is resolved
Anyone but me

Fix - Mobile navigation language overflow

---

assets/templates/partials/header.tmpl

Remove unnecessary `role="text"` from main navigation. This was added to fix issue on iPhone VoiceOver but was not actually needed. 
Tested in NVDA and VoiceOver.
1. Load any page
1. See that the main navigation links that expand contain a role="text"
1. Switch to this branch and `babbage` branch `fix/misc-remove-unnecessary-role`
1. See that the labels are read correctly by screen readers.
Anyone but me

Fix - Remove unnecessary role from main nav

---

assets/templates/feedback.tmpl

Add missing fieldset and legend to wrap radio buttons on feedback form e.g. https://www.ons.gov.uk/feedback?service=cmd
1. Visit the feedback form
1. Run wave and see that it alerts that there is no fieldset wrapping the radio buttons
1. Switch to this branch `fix/misc-feedback-fieldset-legend`
1. See that the styling is unchanged but the alert in wave is resolved.
Anyone but me

Fix - Feedback page fieldset legend

---

assets/templates/datasetLandingPage/version-list.tmpl

Remove unnecessary and duplicated id from `dataset-version-list` page.
e.g. https://develop.onsdigital.co.uk/datasets/cpih01/editions/time-series/versions
Haven't been able to see this locally so changing it blind as really tiny.
1. Load the page
1. See that there are duplicated ids
1. See that they are gone
Anyone

FIx - Remove duplicate id dataset-version-list page

---

assets/templates/partials/filter-selection.tmpl
config/config.go

When adding a filter to the selected filters in CMD hierarchy and geography pages then the ids would be duplicated between input and the remove link.
1. Load a CMD hierarchy or geography page
1. Select a filter
1. See that the ids are duplicated
1. Switch to this branch and sixteens `fix/duplicate-ids-cmd-filters`
1. See that there are no ids when added by JS or on refresh
Anyone but me

Fix - CMD filters duplicate ids

---

assets/templates/dataset-filter/age.tmpl
assets/templates/dataset-filter/time.tmpl

On CMD filter pages for Time and Age there were missing `fieldset`s around the radio groups (found using WAVE). Additionally there was an incorrect `id` in a `label` `for` attribute on Age filter page (found using AXE).
1. Visit CMD Age and Time pages
1. Note the issues above
1. See they are resolved
Anyone but me

Fix - CMD filters - Invalid for on label and missing fieldsets

---

assets/templates/datasetLandingPage/static.tmpl
config/config.go

Fix issue on dataset landing page with invalid anchor within a `dl`.
Tried wrapping anchor in div but didn't work 😭 
Change has no noticeable affect to screen readers.
1. Load a dataset landing page
1. See there are invalid (non `dt`, `dd` or `div`. Not `a`) elements children of a `dl` (AXE)
1. Switch to this branch and sixteens brach `fix/invalid-dl`
1. See this has been switched to a `ul`, `li` and `div`.
Anyone but me

Fix - Invalid dl on dataset landing pages

---

assets/templates/dataset-filter/filter-overview.tmpl
config/config.go

Use classes instead of ids as there are multiple filter options on the filters overview page
1. Visit the filter overview page for a dataset with multiple filters
1. See that the ids for the list item and text content are duplicated
1. Switch to this branch and sixteens branch `fix/duplicate-ids-cmd-filter-options`
1. See that this issue is now resolved and exiting click and hover functionality is maintained
Anyone but me

Fix - Duplicate ids - CMD filters overview page

---

assets/templates/geography/list.tmpl

Ensure that headings increase by just one. Found using axe
This is a blind (I don't have local data) for the page where this occurrs https://develop.onsdigital.co.uk/geography/countries
1. Visit the page (if you can)
1. See the issue mentioned above
1. See that the issue is resolved and the layout is unchanged
Anyone but me

Fix - Geography - Ensure the headings only increment by 1

---

assets/templates/dataset-filter/age.tmpl

Fix a missing quote and improve label as per UX.
1. Visit CMD age filter page
1. See that all ages options does not include min/max age
1. See that this is resolved
Anyone but me

Fix - Accessibility - CMD Age filter

---

assets/templates/search.tmpl
assets/templates/search/results.tmpl
assets/templates/search/sort.tmpl

- Add sort bar to the search page
- Able to now sort the search results (without using `babbage`)
- When it is non-js, a sort button is available to do the same functionality
- Check if the code makes sense
- Can test locally by running `web` instances, `dp-search-query`, `dp-frontend-search-controller` and then on the browser, go to `http://localhost:20000/search`
- Search for `housing` for example and then sort the results to `release_date` (or whichever) to see the search results sorted to date order (in this case)
**Describe who worked on the changes, so that other people can review.**
Anyone - Justin made the changes

add sort to search page

---

assets/templates/dataset-filter/age.tmpl

Add additional details to the ages to add and not for `HasAllAges` option.
This was a blind change as I don't have it locally and missed that there are two add all ages options.
1. Review the code
1. See that it now applies to the list of ages selection not the `HasAllAges`
Anyone

Fix - CMD Ages - blind change

---

assets/templates/homepage.tmpl
assets/templates/homepage/around-the-ons.tmpl
assets/templates/homepage/in-focus.tmpl
assets/templates/homepage/main-figures.tmpl
assets/templates/homepage/promos.tmpl
assets/templates/partials/banners/census.tmpl
assets/templates/partials/banners/survey.tmpl
assets/templates/partials/header.tmpl
config/config.go

Completely rework the homepage styling to remove fixed heights so that when the letter spacing is changed the content expands and the content is not obscured.
One known issue is that there is some unintended spacing on the tablet (breakpoint md) when the text spacing is there. This seems unavoidable without JS which seems unnecessary. This has been signed off by @armstrongb  
This works on all supported browsers.
1. Visit any page
1. Run the letter spacing bookmarklet
1. See that content is obscured or the design is broken
1. Switch to this branch, dp-frontend-renderer branch  `fix/letter-spacing-homepage` and babbage branch `fix/letter-spacing`
Anyone but me

Fix - Letter spacing

---

assets/templates/homepage/in-focus.tmpl

Update number of maximum tiles in the In Focus section from 4 to 8. This means publishing can provide more content to the In Focus section on the homepage.
- Update your homepage data.json to include _up to_ 8 objects. The updated logic in the template file should ensure that the In Focus tiles are laid out properly
- You could also test in Florence with [this PR]() that the limit has been increased to 8 in the Edit Homepage screen too. It'd then be a case of following the full Edit Homepage publishing journey and viewing the changes afterwards.
Anyone

update to exclude margin on end of row for up to 8 tiles

---

assets/templates/datasetLandingPage/filterable.tmpl
config/config.go

Inside the other download options box, the text was floating right on mobile devices and looked awkward. Text now floats left. 
Go here: http://localhost:20000/datasets/cpih01/editions/time-series/versions/1
See that on mobile view, the text in the other download options box is floating right. 
Pull this branch and the text should be left aligned. 
Anyone but me.

make text float left on mobile

---

assets/templates/main.tmpl

- Removed meta tag on main.tmpl
- This is not used by search engines for positive reasons anymore
- Can be used by some engine to help identify spam (potentially bing)
- Removed to avoid us accidentally getting higher spam ratings and having unnecessary bloat
The following used to be present: (note this is on homepage, other pages have keywords and are not just empty)
But now it isn't:
Note: model data still has keywords stored as this can be used in Structured Data to improve SEO
Open the DOM on a number of pages (inspect elements). Go to the <head> tag and inside its contents check for <meta> tags. Ensure that none have the property name="keywords".
Pages should all still load and function as they did before

Keywords meta tag removed

---

config/config.go

Version of sixteens updated to version 1.4.5 which includes:
- Feedback form focus highlighting is now in line with the rest of the website
- Feedback form error highlighting is now in line with the rest of the website
- Uncomputable size in form-helper fixed
- Filter pages age and time now have a new accessibility feature of reading out errors on form input
Check that this is the correct latest release of sixteens
Check that the version of sixteens has indeed been updated

Update version of sixteens to v1.4.5

---

config/config.go

- Purpose is no longer used so removed the JS from it on feedback form
- Form wasn't reading out form warnings, as this is now required on other areas of the website this has now been implemented here too
- IE10 doesn't support outline-offset and so was still showing double border on focus. It no longer does.
- There was an issue with voiceover fighting for some users: introduced aria-live 'polite' for such situations.
Check that this is the correct latest version of sixteens
Check that no other code has slipped into this release

Update version of sixteens

---

assets/locales/active.cy.toml
assets/locales/active.en.toml
assets/templates/dataset-filter/time.tmpl
assets/templates/datasetLandingPage/filterable.tmpl
assets/templates/feedback.tmpl
assets/templates/homepage.tmpl
assets/templates/homepage/in-focus.tmpl
assets/templates/homepage/latest-releases.tmpl
assets/templates/homepage/main-figures-error.tmpl
assets/templates/homepage/main-figures-none.tmpl
assets/templates/homepage/main-figures.tmpl
assets/templates/main.tmpl
config/config.go
go.mod
go.sum

The following must be deployed just before this is
Noelles work I think that is contained in this. Would be good if someone else can verify/sanity check:
Check that nothing has slipped into the release that shouldn't be in it
Check that everything in this release has been PO signed off

Release 1.31.0

---

assets/templates/error.tmpl

Hotfix to be implemented so that 404 error page can display a warning to users that some datasets will have been moved owing to the Neptune migration.
This PR specifically includes the dataset migration warning message in the 404 page
- Check in conjunction with [this dp-frontend-router PR](https://github.com/ONSdigital/dp-frontend-router/pull/242)
- Go to a page locally that'll give you a 404 - check that the copy and design matches [this prototype](https://deploy-preview-6--dp-prototypes.netlify.app/prototypes/status-banner/404-page) 
Anyone

implement neptune migration warning message into 404 pages

---

assets/templates/partials/feedback.tmpl
assets/templates/partials/footer.tmpl
config/config.go

- Update feedback bar styling
- Removed check for `ShowFeedbackForm` to display feedback bar on all pages (yes even error pages and feedback form page). [Product decision]
Anyone

Update feedback bar styling and display by default

---

assets/templates/dataset-filter/filter-overview.tmpl

Empty alert being read by screenreader. 
Go to filters page, select filters and hear that empty alert is read aloud. 
Pull this branch, go to filters page, select filters and hear that empty alert is not read by screenreader. 
Anyone but me.

remove unused code

---

assets/templates/homepage/main-figures.tmpl

Trend indicator is wrong on employment and unemployment. Whilst this issue is being investigated these indicators are to be removed to reduce confusion and possibility of showing wrong values
Check homepage that the employment and unemployment main figures section no longer show the trend indicators.
Check this on multiple browsers and viewports to ensure homepage doesn't start behaving weird. e.g. misalign
Frontend dev

Temporarily remove main figure trends on homepage

---

assets/templates/homepage/main-figures.tmpl

We need to remove the trend indicators ASAP on the homepage for employment and unemployment
Note this contains the changes from https://github.com/ONSdigital/dp-frontend-renderer/pull/541 . 
These changes are desired to go into production before other tasks on develop are signed off.
Check that these indicators have been removed and that everything still aligns ok on the homepage
Frontend dev or TL

HOTFIX RELEASE - Remove trend indicators for employment and unemployment

---

assets/templates/main.tmpl

Remove unnecessary meta tags `cleartype` and `X-UA-Compatible` since these are no longer needed for IE11. 
Go to any page and inspect it, see the meta tags `cleartype` and X-UA-Compatible`. Pull this branch, see these tags are no longer present. 
Anyone but me.

remove unnecessary meta tag

---

assets/templates/main.tmpl
assets/templates/partials/header.tmpl

Remove conditional formatting for browsers older than IE11 since we no longer support these browsers.
Inspect any page, see conditional formatting that supports older IE browsers. Pull this branch, inspect any page and see there is no longer conditional formatting.
Anyone but me.

remove code for browers no longer supported

---

assets/templates/dataset-filter/age.tmpl
assets/templates/dataset-filter/filter-overview.tmpl
assets/templates/dataset-filter/hierarchy.tmpl
assets/templates/dataset-filter/list-selector.tmpl
assets/templates/dataset-filter/preview-page.tmpl
assets/templates/dataset-filter/time.tmpl
assets/templates/datasetLandingPage/edition-list.tmpl
assets/templates/datasetLandingPage/filterable.tmpl
assets/templates/datasetLandingPage/version-list.tmpl
config/config.go

On all CMD templates pages the following has been updated
change all font-size(16,17) to 18 and line-height to 32
all h1 to===>font-size to 38 and line-height to 48
all h2 to===> font-size to 32 and line-height to 40
all h3 to===>font-size to 24 and line height to 32
Updated changes in sixteen repo is required when viewing the CMD pages
Update necessary <li> font size to 18  and line-height 32
Check all changes are correct as per ticket
https://trello.com/c/ImaXOlpP/119-typography-on-cmd-pages-is-incorrect-too-small-s4-1-day
Run the CMD journey and check for the changes
Note: https://github.com/ONSdigital/sixteens/pull/256  is required to see the changes in this PR
Anyone

Update font on CMD pages

---

assets/templates/partials/banners/covid.tmpl

The only change made was to decrease the margin size. It appears other changes to css in sixteens has corrected the banner from covering the menu. 
Look at the homepage and see a large gap between top of banner and bottom of menu on small and medium screens. Inspect page to see that the margin on top is 7 and 5 respectively. Pull this branch and inspect page to see top margin is now 3. 
Anyone but me.

decrease margin size

---

assets/templates/dataset-filter/hierarchy.tmpl

Fixed an issue where the 'browse by x type' text in hierarchy options overflows when it's a number greater than 9, specifically by increasing the width of the 'browse by' element:
**Before**
**After**
Sense check. Go to a hierarchy filter page and seeing that the styles look okay
Make sure no other changes present
Anyone

Updated styling for hierarchy options

---

config/config.go

Update Sixteens to newest version. This fixes the bug in the CMD filter journey where checkbox interactions make a call to the `remove-all` endpoint instead of `update` after the user clicks "Remove All" to clear their basket. This was due to a bug in the JS enhancement in Sixteens where the request URL was not being properly updated.
Sense check that the latest Sixteens version is being used
Anyone

Update Sixteens version

---

assets/templates/search.tmpl
assets/templates/search/pagination.tmpl
assets/templates/search/results.tmpl
render/helpers.go
render/helpers_test.go
service/service.go

- Add search pagination to the search page
- Add a helper function `Add`
- Check if the code makes sense
- Can test locally by running web instances, `dp-search-api`, `dp-frontend-search-controller` and then on the browser, go to `http://localhost:20000/search`
- Go to the bottom of the web and move to the next page. You will notice that the search results will change to show the next offset of search results
- Change the limit of results to be displayed and the number of results available on the screen will be updated accordingly
Please note that updates to `dp-frontend-search-controller` is still in PR (https://github.com/ONSdigital/dp-frontend-search-controller/pull/16), therefore you need …

add search pagination

---

assets/templates/homepage/main-figures.tmpl

Fixed time series explorer link in the home page so that it's relative to the domain rather than hardcoded to the prod site
Load the ons home page locally from the develop branch then then click on the link "From our time series explorer" next to the "Main figures" title to navigate to the time series explorer page. See the address of the time series explorer page is incorrectly being directed to the prod website (ons.gov.uk). Check out this branch then after following the time series explorer link on the homepage, the time series explorer page address should be localhost:8081.
Anyone

edited link to time series tool to use relative path

---

assets/templates/partials/feedback.tmpl

Added `role="status"` and `aria-live="polite"` so that screenreader will announce changes to div. 
Go to feedback form on homepage and hear that NVDA does not read out confirmation on all browsers. Pull this branch along with this branch [https://github.com/ONSdigital/sixteens/pull/262](url)  and hear NVDA read confirmation message across all browsers.
Preferably a frontend dev - Ravi, Dan, Jon.

make screenreader announce confirmation message

---

assets/templates/datasetLandingPage/filterable.tmpl
assets/templates/datasetLandingPage/nomis.tmpl
assets/templates/datasetLandingPage/static.tmpl

Fixed bug where href associated with national statistics image pointed to a page which no longer exists.
Review link has indeed been updated and points to the correct page.
Anyone.

Fixed bug where href associated with national statistics image pointed to a page which no longer exists.

---

assets/templates/dataset-filter/filter-overview.tmpl
config/config.go
go.mod
go.sum

- Reinstated error container 
- Included message to handle when no js is enabled (same as JS version)
- Updated dependencies
- Make sure you have [CMD data setup](https://github.com/ONSdigital/dp/blob/main/guides/INSTALLING.md#cmd) and the overall journey working locally to see changes 
- Pull the branch with changes to the [dp-frontend-filter-dataset-controller](https://github.com/ONSdigital/dp-frontend-filter-dataset-controller/tree/fix/error-handling-on-filter-journey-no-js)
- Disable JS
- Check that an error message is shown if you click 'apply filters' with no filters added
- Check spelling
Anyone but me

Fix to error handling on filter journey when js is disabled

---

assets/templates/dataset-filter/filter-overview.tmpl
config/config.go

- Refactored dimension names container to use `flex`. Multiline titles now fill the container and align correctly.
- Other design tweaks to prevent unnecessary type trim 
_...before_
_...after_
Requires CMD journey to be setup locally
Sense check
Pictures show changes ^
Anyone but me

Fix dimension names being chopped off

---

assets/templates/homepage/census-tile.tmpl
assets/templates/partials/banners/census-tile-sm.tmpl

Removed `title` and `id`. Used `alt` instead. 
See that `alt` displays the correct information ("Census 2021")
https://trello.com/c/g79Z7jV2/803-census-logo-id-parsing-error
**Small viewport:** 
**Medium viewport**
**Large viewport**
Anyone but me.

use alt text and remove title

---

assets/templates/search/results.tmpl
render/handler.go

Add `safeHTML` to search results to allow for highlighting
Must have the following services running in order to view this change: 
- `dp-search-api`
- `dp-frontend-search-controller`
-  set `SearchRoutesEnabled` to `true` in the config of the `dp-frontend-router`
See that tests pass. Pull branch and see that new yellow highlighting `<em class="highlighting">` is applied to search results. Should look like the image below. 
Anyone but me.

allow html for search highlighting

---

render/helpers.go
render/helpers_test.go

Added further processing of string if over a certain length i.e. if the string containing the date range holds two months and a year. 
Fix needed because original code would move year provided by the start month and put it after the end month resulting in 2020 DEC - FEB becoming DEC - FEB 2020 when it should be DEC - FEB 2021.
Further discussions has resulted in the desired output being DEC 2020 - FEB 2021 and the code added reflects that desire.
LGTM / Feel free to pull and check locally.
Someone familiar with GO

Added further processing if string recieved is long enough

---

ci/build.yml
ci/unit.yml
go.mod
go.sum
handlers/homepage/handler_test.go
routes/routes.go
service/service.go

A security vulnerability in the `gorilla/pat` router allows a maliciously crafted url to act as an open redirect. Although the dp-frontend-renderer is deprecated and not directly available externally, an attacker could theoretically craft a malicious redirect eg. in an email to an internal staff member. `gorilla/mux` does not suffer from the same vulnerability as it correctly escapes the url supplied to the Location header when performing a 301 redirect.
Ensure the service no longer uses `gorilla/pat` for routing and that an appropriate test exists and passes.
Anyone but me

Replace gorilla/pat with gorilla/mux (+go 1.17)

---

assets/templates/partials/feedback.tmpl

Feedback partial is redirecting to nonexistent `feedback-thanks` page causing a `503` on the website along with the message "Something went wrong, try using our feedback form."
See that link to `feedback-thanks` has been removed. 
Frontend dev

remove redirect
