- Dockerfile
- Jenkinsfile
Initial `Dockerfile` and `Image` build stage.
> Docker image

- vendor/github.com/ONSdigital/dp-frontend-models/LICENSE.md
- vendor/github.com/ONSdigital/dp-frontend-models/model/errorResponse.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/homepage/model.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/metadata.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/page.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/taxonomy.go
- vendor/vendor.json
Add missing vendored dependency
vendor/github.com/ONSdigital/dp-frontend-models should be there
> add missing dependency

- Jenkinsfile
Deploy to discovery environment when dd-develop is pushed to.
Code review should be fine.
Anyone but myself.
> Deploy dd-develop to discovery environment

- README.md
Add some documentation explaining how to create new page types
Check the readme makes sense
> add some documentation

- config/config.go
Update renderer to use React application from commit e761a04
Dataset app rendering from commit code e761a04
Anyone but me
> Update to frontend version e761a04

- assets/templates.go
- assets/templates/dd/splash.tmpl
- handlers/dd/splash/handler.go
- main.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/dd/splash/model.go
- vendor/vendor.json
Add splash page to the renderer
* Start the renderer
* `curl -X POST -d '{}' http://localhost:20010/dd/splash`
* Get a splash page!
> add data discovery splash page to renderer

- Jenkinsfile
See https://github.com/ONSdigital/dp-content-resolver/pull/7
> remove ecr login

- assets/templates.go
- assets/templates/dd/disabled.tmpl
- handlers/dd/disabled/handler.go
- main.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/dd/disabled/model.go
- vendor/vendor.json
Added a disabled page
* Start the renderer
* Check `curl -d '{}' http://localhost:20010/` returns the disabled page
> add disabled page to renderer

- render/render.go
Handle panics from unrolled render when rendering HTML or JSON.
Renderer still runs as before.
Anyone
> Handle panics in renderer

- config/config.go
> Feature/merge v1.0.3

- assets/templates.go
- config/config.go
Fix IE11 getting stuck on the 'generating your file' screen on the download journey.
All normal journeys work on develop.discovery.onsdigital.co.uk on Chrome and IE11.
Anyone but me.
> Dd develop -> dd master

- config/config.go
React app updated to latest
Run it locally to make sure it works
Anyone but me
> Dd develop

- config/config.go
Release latest version of react app
Anyone
> Update to latest React app (cb31678)

- Makefile
- handlers/homepage/handler_test.go
Unit tests have been broken for a while.. so here's the fix!
> Fix unit tests

- README.md
Added whitespace
confirm commit is verified
Anyone
> Add whitespace to readme

- config/config.go
Update sixteens for cmd-develop
> Update sixteens version for cmd-develop

- config/config.go
> Updated sixteens path for the renderer

- assets/templates/dataset-filter/hierarchy.tmpl
- assets/templates/partials/filter-selection.tmpl
UI changes to the hierarchy filter journey.
Pull all the things.
Use branch feature/hierarchy-update on the following repo's
dp-frontend-renderer
dp-frontend-filter-dataset-controller
sixteens
Go to the CPI dataset, filter and then view the hierarchy dimension. Check that the ui changes match the UX from the following ticket: https://trello.com/c/ugRFl9Gl
Anyone.
> Changes to the template markup

- config/config.go
> Updated path for sixteens build

- handlers/homepage/handler_test.go
Update the homepage test to use the correct depedency for the renderer (i.e. the one from go-ns), so that the tests pass.
Run tests and check they pass.
Anyone.
> Fix homepage test

- assets/templates/dataset-filter/preview-page.tmpl
> Attempt to fix preview

- README.md
Add config to readme
Read the readme
> add config options to readme

- config/config.go
Updated config for the sixteens path.
Check that the commit code is correct (sixteens -> feature/gtm-datalayer)
Anyone.
> Updated the config for sixteens

- main.go
Add a template function that turns string into safe slugs. 
In a template add `{{slug .someData}}` and check that it's been properly turned into a slug.
Anyone but me.
> Slug template function

- config/config.go
> Bump sixteens

- config/config.go
Update to latest CMD sixteens (`f36b72f`), so that the feedback form confirmation HTML has an ID on it - helping fix acceptance tests.
Check the correct commit is added and the Sixteens build is passing.
Anyone but me.
> Sixteens f36b72f

- assets/templates.go
- assets/templates/dataset-filter/age.tmpl
- assets/templates/dataset-filter/hierarchy.tmpl
- assets/templates/dataset-filter/list-selector.tmpl
- assets/templates/dataset-filter/preview-page.tmpl
- assets/templates/dataset-filter/time.tmpl
- Setup and teardown now remembers your previous mongo state and restores it
- Info on how to run preview tests
- You will need a valid instance_id from a CPI import for preview
- Set the environment variable
`export INSTANCE_ID=<instance_id>`
run `./run.sh`
The setup and teardown will remember your previous mongo state and restore it at the end
Team A
> Preview web tests

- assets/templates.go
- vendor/github.com/ONSdigital/dp-frontend-models/model/datasetEditionsList/model.go
- vendor/vendor.json
Vendor in missing model field
Go to editions list page
Verify it loads
Anyone
> Add missing vendor

- config/config.go
> update sixteens path

- assets/templates.go
> Rebuild assets

- assets/templates.go
- config/config.go
> Updated sixteens config for ie feedback form error fix

- assets/templates.go
- config/config.go
> reverted to a previous sixteens commit

- assets/templates.go
- config/config.go
This reverts commit f4776ac2bc771e0538c9e67c8560d6f2709a6151.
> Revert "reverted to a previous sixteens commit"

- config/config.go
> sixteens path change

- config/config.go
> updated config path for sixteens

- taxonomy-redirects.yml
Added 4 new datasets to support ASHE release. 
Check 'exit beta' button works for these four datasets
> Update taxonomy yml for new datasets

- dp-frontend-renderer.nomad
* Configure the healthy threshold and deadline
* Enable auto rollback on failed deploy
* Increase the stagger time to allow enough time for scheduling
* Allow for splitting the nomad classes
Ensure configurations are valid and logical.
Anyone but me.
> Improve nomad plans

- assets/templates.go
- assets/templates/partials/latest-release-alert.tmpl
Created a new alert style for cmd.
Checkout sixteens on `feature/new-alert`.
Go to the filter overview page and preview page of a previous version.
Check that the new banner matches ux.
Anyone.
> Updated latest release  partial for new alert

- config/config.go
Update sixteens reference for download href link fix
> Update sixteens reference for download href link fix

- config/config.go
Check for undefined values before attempting to read filter download url
> Check for undefined values before attempting to read filter download url

- assets/templates.go
- config/config.go
Update sixteens build commit ID 1f31a7c
Anyone
> Update sixteens commit ID

- taxonomy-redirects.yml
New link added for opss and well-being
Make sure I got the structure fight this time :-)
> new link added for opss and well-being

- assets/templates/dataset-filter/filter-overview.tmpl
- assets/templates/partials/latest-release-alert.tmpl
it fixes 
https://trello.com/c/GitELoKV/3088-filter-options-page-mobile-view
UX  spec
https://xd.adobe.com/spec/e8935a65-c21f-4ef7-a205-e27c9af3214e/#
by adding md and sm to the div padding/margin
https://beta.ons.gov.uk/filters/0e409f49-fb11-45d3-9297-3f60c3a1ab4b/dimensions
all
> filter option page optimised for mobile view

- config/config.go
update sixteens pattern library 
jon - crispin
> update sixteens pattern library

- assets/templates.go
Rebuild templates assets to fix conflict text that is rendering on CMD develop.
Check that geography homepage bytes are different.
Anyone but me.
> Fix conflicted assets

- dp-frontend-renderer.nomad
Restrict deployment to only non-mount instances to ensure the special mount instances are kept clear for the apps that require them.
Ensure the node pattern no longer matches the mount nodes.
Anyone but me.
> Restrict deployment to non-mount instances

- config/config.go
Update assets path to include sixteens changes for excel limitation warning
sanity check
anyone
> Update assets path

- dp-frontend-renderer.nomad
The renderer was ending up deployed on the reserved 'mount' instances
that need to be kept clear for those apps that need the mount.
Ensure the nomad plan is still valid.
Anyone but me.
> Fix nomad class constraints

- dp-frontend-renderer.nomad
Add healthcheck to nomad plan.
Ensure nomad plan is valid.
Anyone but me.
> Add healthcheck to nomad plan

- config/config.go
Updated version of sixteens in use to:  49e78a9124316a2b8afd507e9ceb961c4734fc2c
Checkout the branch, ensure everything looks like it should
> Updated version of sixteens in use

- assets/templates/datasetLandingPage/filterable.tmpl
Fix the padding on a title
Checkout branch ensure titles in editions is in the right place
Anyone except from me
> Fix for CMD title padding

- vendor/vendor.json
> Fix conflict

- assets/templates.go
- config/config.go
Update sixteens commit id to `7a7f0db`
Anyone
> Update sixteens commit id to 7a7f0db

- config/config.go
Update sixteens commit to support jquery change
> Update sixteens commit to support jquery change

- assets/data.go
- config/config.go
Update version of sixteens
Sanity check commit 
Anyone
> Update version of sixteens

- render/handler.go
Remove JSON payload log line to prevent unpublished content being logged
Sanity check 👀
Anyone
> Remove JSON payload log line

- config/config.go
Update version of Sixteens to include recent cookies changes.
Ensure that the commit hash included in the sixteens config is `8ec39ec` 
Anyone but me
> update sixteens version

- assets/templates/partials/json-ld/base.tmpl
Removed `-` from hasField function calls
Ensure it's removed
Anyone but me
> removed - from hasField interpolation

- Makefile
- ci/audit.yml
- ci/scripts/audit.sh
Add vulnerability audit to CI build
Anyone
> Add vulnerability audit to CI build

- config/config.go
Updated the sixteens CDN URL for the most up-to-date homepage changes
Check that the change matches the most recent Sixteens commit ID
Anyone but me
> update sixteens cdn url

- config/config.go
> Updated version of sixteens

- assets/locales/active.cy.toml
- assets/locales/active.en.toml
- assets/templates/homepage.tmpl
- assets/templates/partials/homepage/main-figures.tmpl
- go.mod
- go.sum
- handlers/homepage/handler_test.go
- Update main figures to use new page model
Anyone
> Update main figures to use new page model

- assets/templates/partials/homepage/main-figures.tmpl
Fix inflation timeseries ID value. Was a 0 (zero) when it should be O
Anyone
> Fix inflation timeseries ID value. Was a 0 (zero) when it should be O

- assets/templates/homepage.tmpl
- assets/templates/homepage/main-figures.tmpl
Main figueres in same dir as other sections
Mobile had an added '-' for GDP which shouldn't have been there 
Check homepage renderes correctly
> Fix for negative value on mobile and moved files

- assets/templates/homepage/main-figures.tmpl
Analysis section missing from GDP and UK Population estimates
Check these sections display correctly and have the correct links
> Analysis added to mobile and desktop for GDP and pop

- assets/templates/dataset-filter/preview-page.tmpl
- assets/templates/datasetLandingPage/static.tmpl
Fix GTM tags download on data download links
Sanity check
Anyone
> Fix GTM tags download on data download links

- assets/templates/homepage/in-focus.tmpl
Update link for Faster Indicators to go to correct page rather than weekly deaths
Ensure above change has been applied
Anyone but me
> fix faster indicators link

- assets/templates/homepage/main-figures.tmpl
- render/helpers.go
- render/helpers_test.go
- service/service.go
New helper in renderer for formatting time-series time periods to more human accessible format.
Tests have also been added along with templates now using the new helper function
Check the months used for each quarter are correct
Check tests cover wide enough coverage of new helper function
Take the new helper function out for a spin
Ensure these changes meet criteria of UX design
> Dates now more human readable on homepage

- assets/templates/dataset-filter/preview-page.tmpl
Fix quote bug in preview page gtm tags, causing the page to fail to render
Can you load a preview page?
anyone
> Fix quote bug in preview page gtm tags

- assets/templates/datasetLandingPage/filterable.tmpl
Add GTM tags for other downloads on filterable (CMD) dataset landing page
Sanity check
Anyone
> Add GTM tags for other downloads on filterable (CMD) dataset landing page

- assets/templates/homepage.tmpl
- assets/templates/homepage/main-figures.tmpl
- assets/templates/homepage/promos.tmpl
- assets/templates/partials/banners/census.tmpl
- assets/templates/partials/banners/survey.tmpl
- Add new markup for medium viewport of main figures and release calendar
Requires https://github.com/ONSdigital/sixteens/pull/193 to see promo boxes working correctly
Anyone
> Homepage release calendar medium viewport fixes

- assets/locales/active.cy.toml
- assets/locales/active.en.toml
- assets/templates/homepage.tmpl
- assets/templates/homepage/latest-releases.tmpl
- assets/templates/homepage/main-figures.tmpl
- assets/templates/homepage/promos.tmpl
- assets/templates/partials/banners/census.tmpl
- assets/templates/partials/banners/survey.tmpl
- go.mod
- go.sum
Add release calendar tile to homepage
- Pull sixteens branch `feature/list-tiles` - https://github.com/ONSdigital/sixteens/pull/191
- Sanity check, browser/device test
Anyone
> Add release calendar tile to homepage

- config/config.go
Update sixteens a3b98cd
Anyone
> Update sixteens a3b98cd

- assets/templates/homepage/latest-releases.tmpl
- go.mod
- go.sum
- Change number of releases on homepage release calendar
Anyone
> Change number of releases on homepage release calendar

- assets/locales/active.cy.toml
- assets/locales/active.en.toml
> Change others to other

- assets/templates/main.tmpl
- assets/templates/partials/gtm-data-layer.tmpl
- Add new partial for GTM data layer
- Add function for reading cookie policy cookie and adding to data layer
Test GTM data layer still works with new partial
Test `analyicsOptOut` property is correctly set in GTM data layer
Anyone
> Add new partial for GTM data layer and add function for reading cookie policy cookie and adding to data layer

- render/helpers.go
Add localise time func so that date/time helpers display the correct date/time 
Anyone
> Add localise time func for helpers to use

- assets/templates/partials/footer.tmpl
Hotfix to update privacy link in footer
Check privacy link is correct
Anyone
> update footer link: /help/privacy => /help/privacynotice

- assets/templates/main.tmpl
- go.mod
- go.sum
- Update frontend models version
- Add check for hide cookie banner value
Anyone
> Fix cookie banner appearing on cookie page

- assets/locales/active.cy.toml
- assets/locales/active.en.toml
- assets/templates/homepage/main-figures-error.tmpl
- assets/templates/homepage/main-figures.tmpl
Add handling for main figures error state
- Switch to `feature/lms-offset-changes` in the homepage controller. Simulate an empty response from Zebedee then homepage-controller and the render should render the main figure as an error (rather than falling over)
Anyone.
> Add handling for main figures error state

- assets/templates/main.tmpl
Pull branch. Inspect page. `lang` and `xml:lang` attributes should be either "en" or "cy". If there is no language property set, the default will be "en". 
Anyone but me!
> set language attribute

- assets/templates/partials/banners/covid.tmpl
Merge covid banner margin tweak
> update top margin across viewports for covid banner

- assets/templates/dataset-filter/age.tmpl
- assets/templates/dataset-filter/geography.tmpl
- assets/templates/dataset-filter/list-selector.tmpl
- assets/templates/dataset-filter/time.tmpl
Add descriptions to add context for a screen reader user when using the CMD filter `Add all` and `Remove all` links.
1. Visit a filter with an add/remove all button e.g time
1. Select the filter and a confusing message read
1. Hear a better message read
Anyone but me
> Fix - Add descriptions for add and remove all buttons

- config/config.go
Update sixteens
See that sixteens is now that the latest commit
Anyone but me
> Update sixteens to the latest version

- assets/templates/partials/banners/cookies.tmpl
- Only trigger GTM on accept cookies
Anyone
> Only trigger GTM on accept cookies

- assets/templates/partials/footer.tmpl
- assets/templates/partials/header.tmpl
Added `aria-label` attributes to the nav elements to ensure that the landmarks are unique for accessibility purposes (audited with Axe and Wave)
Ensure changes make sense and resolve the accessibility audit issue
Anyone
> add aria labels to ensure navs are unique landmarks

- assets/templates/dataset-filter/geography.tmpl
- assets/templates/dataset-filter/hierarchy.tmpl
- assets/templates/partials/feedback.tmpl
Dataset fixes on [CMD filter outputs page](https://www.ons.gov.uk/filter-outputs/45662be9-3262-488e-9108-8b556ad84d8b) and CMD hierarchy and geography pages
1. Fix invalid javascript url causing WAVE validation error in the feedback form close button. 
1. Fix aside should be sibling of main not a child AXE - https://dequeuniversity.com/rules/axe/3.5/landmark-complementary-is-top-level in geography and hierarchy pages
1. See the pages above
1. See the issues mentioned
1. See that they are fixed
Anyone but me
> Data page fixes

- assets/templates/main.tmpl
Added rel=canonical link to direct search engines to the base '/feedback' page
Confirm everything is ok
Anyone
> added rel=canonical link to feedback page

- assets/templates/feedback.tmpl
Wrapped specific radio buttons with if statements to only display under certain conditions
Confirm everything is ok
Anyone
> Updated the conditions for how radio buttons are displayed on feedback page

- assets/templates/dataset-filter/time.tmpl
- config/config.go
- go.mod
- go.sum
Additional work requested
Revert to avoid hold up of work
The below is also reverted
Check that everything from the previous merge has been reverted
> Revert commit merge feature.time-selector

- assets/locales/active.cy.toml
- assets/locales/active.en.toml
- assets/templates/feedback.tmpl
Feedback page and Thank you page now both use localisation. 
Note that although it grabs data from the localisation files the language on the page is always set to English for two reasons
1. We have no Welsh translations for anything on the page
2. The handler never maps the language to the page model so DOM/Template has no idea what language to use so defaults to English
There is a new feedback-controller being made, as right now the handlers are in the dataset-controller. As such it has been discussed with PM that there is no point adding it to the dataset-controller if we are about to rip it out and replace it very shortly. A ticket is being made to capture this though to ensure we implement the language properly on the new controller.
This page now follows the new designs as seen on …
> Feedback Non-JS journey redesign

- config/config.go
Update reference to sixteens
Should see new reference to sixteens
Anyone but me.
> update reference to sixteens

- assets/templates/datasetLandingPage/filterable.tmpl
Did I hear you say 'Eww' the execution of this code is horrendous?
- In line styling
- No feature flag
- Using markdown styling for publications on this non publication related message
- Check that this is accessible enough to all users
- Check this only effects the pages required and not any other
- Check the correct message has been implemented
- Check the links will work on production
- Cross browser check the styling
- Cross device check the styling
- Check spelling etc.
> New warning for filterable dataset landing pages

- assets/templates/datasetLandingPage/filterable.tmpl
Blog post has been published. Link to blog now updated to this blog post for the urgent filter warning banner
Check that the link works, check that this is the correct link
> Add link to actual blog post, now that it has been published

- assets/templates/datasetLandingPage/filterable.tmpl
Remove Neptune migration banner, now that the Neptune migration is complete.
Sanity check
Anyone
> Remove Neptune migration banner

- assets/templates/datasetLandingPage/filterable.tmpl
Hot fix from master - Remove Neptune migration banner
Sanity check
Anyone
> Hot fix from master - Remove Neptune migration banner

- assets/locales/active.cy.toml
- assets/locales/active.en.toml
- assets/templates/homepage/around-the-ons.tmpl
Add secure data tile to "Around ONS" section
Anyone
> Add secure data tile to "Around ONS" section

- Makefile
Fix ci audit
See makefile has been updated. 
Anyone but me.
> fix ci audit

- assets/templates/homepage/around-the-ons.tmpl
- assets/templates/homepage/in-focus.tmpl
- assets/templates/homepage/main-figures.tmpl
Add GTM data attributes for link tracking
Anyone
> Add GTM data attributes for link tracking

- assets/templates/homepage/around-the-ons.tmpl
- assets/templates/homepage/in-focus.tmpl
Fix not valid data tags. Was missing `data-`. C&P error
Check `data` attributes are now valid
Anyone
> Fix not valid data tags

- assets/templates/partials/banners/census-tile-sm.tmpl
Matched aria-labelledby with it's ID. 
See that the id and aria-labelledby match. 
Anyone but me.
> mismatching id tags

- assets/templates/main.tmpl
> Add black banner

- assets/templates/main.tmpl
- config/config.go
Add emergency banner with content
Anyone
> Add emergency banner with content

- assets/locales/active.cy.toml
- assets/locales/active.en.toml
- assets/templates/homepage/census-tile.tmpl
- assets/templates/partials/banners/census-tile-sm.tmpl
Reworded Census Tile
Verify the code.
Anyone with understanding of ONS homepage rendering.
> Reword census tile on homepage for Census 2021 completion.

- assets/locales/active.cy.toml
- assets/locales/active.en.toml
- assets/templates/feedback.tmpl
Fixed the page feedback form not submitting
- Removed duplicate Ids
- Fixed invalid markup
- Applied missing css classes
- Edited confusing URL label
Pull branch locally and go to localhost/feedback and localhost/feedback/thanks. Check markup is valid and design looks as per design system
Anyone but me
> Fix feedback form - improved markup to produce accessible and valid html

- config/config.go
Updating sixteens to latest version
Anyone but me
> Updating sixteens to 406b9ac

- assets/templates/search/results.tmpl
- go.mod
- go.sum
Prevent 'keywords:' displaying when no keywords are available
Anyone
> Prevent 'keywords:' displaying when no keywords are available

- assets/locales/active.cy.toml
- assets/locales/active.en.toml
- assets/templates/search.tmpl
- assets/templates/search/department.tmpl
- go.mod
- go.sum
> Add search departments

- assets/templates/search/sort.tmpl
- go.mod
- go.sum
Add additional suggestions to search if no results returned
Anyone
> Add search additional suggestions

- MIGRATION.md
- README.md
Detailing files that have been migrated from the `renderer` to the `dp-renderer` library
- Sense check
- Spell check
Anyone but me
> Adding migration info

- assets/templates/partials/banners/covid.tmpl
Fix focus position on covid banner
From:
To:
Anyone
> Fix focus position on covid banner

- assets/templates/search/sort.tmpl
Add spelling suggestions into search
Anyone
> Add spelling suggestions into search

- assets/templates/partials/header.tmpl
Add spelling suggestions into search
Anyone
> Release 1.46.0

- assets/templates/partials/banners/covid.tmpl
- config/config.go
- Fix covid banner focus
- Update to latest version of sixteens
Anyone
> Fix covid banner focus

- assets/templates/search/sort.tmpl
Remove 'sorted by {{sort-type}}' text from search
Anyone
> Remove 'sorted by {{sort-type}}' text from search

- config/config.go
> bump sixteens 6305064

- README.md
> fix default port in README.md

- assets/templates/homepage/census-tile.tmpl
- assets/templates/partials/banners/census-tile-sm.tmpl
- assets/templates/partials/header.tmpl
- a11y fixes for covid banner
- remove sorted by text from search
- update default port in readme
Anyone
> Release 1.47.0

- assets/templates/main.tmpl
Add canonical link to first page of old search
Anyone
> Add canonical link to old search first page

- MIGRATION.md
Update migration doc for search templates
Anyone
> Update migration doc for search templates

- config/config.go
- config/config_test.go
Bump sixteens to the latest version to skip over build issues with the
version of sixteens that is currently being referenced.
Ensure that the commit ref used matches the latest sixteens commit to `main`.
Anyone but me.
> Bump sixteens to latest version

- assets/templates/homepage/census-tile.tmpl
- assets/templates/partials/banners/beta.tmpl
- assets/templates/partials/banners/census-tile-sm.tmpl
- assets/templates/partials/banners/covid.tmpl
- assets/templates/partials/banners/emergency.tmpl
- assets/templates/partials/banners/service-message.tmpl
- assets/templates/partials/header.tmpl
- config/config.go
- config/config_test.go
- go.mod
- go.sum
In this release:
* Add the emergency banner capability
> Release 1.52.0

- assets/templates/homepage/census-tile.tmpl
- assets/templates/partials/banners/census-tile-sm.tmpl
Corrected a link as requested here:
https://trello.com/c/JOb1QTuI/1103-develop-production-issues
Have a look at the code
Anyone
> corrected a link

- assets/templates/main.tmpl
- Remove reference of search as the search pages have migrated to using `dp-renderer`
- This piece of code has been added in https://github.com/ONSdigital/dp-renderer/pull/98
- Check if the code changes make sense
**Describe who worked on the changes, so that other people can review.**
- Anyone
> remove checking search type

- config/config.go
- config/config_test.go
Update reference to sixteens with latest commit hash with js changes for feedback form. 
See that commit has matches commit hash in latest release: https://github.com/ONSdigital/sixteens/releases/tag/v1.4.8
Anyone
> update commit hash with js for feedback form

- config/config.go
- config/config_test.go
updated sixteens version
no special instructions
anyone
> updated sixteens version

- assets/templates/cookies-preferences.tmpl
- assets/templates/dataset-filter/age.tmpl
- assets/templates/dataset-filter/filter-overview.tmpl
- assets/templates/dataset-filter/geography.tmpl
- assets/templates/dataset-filter/hierarchy.tmpl
- assets/templates/dataset-filter/list-selector.tmpl
- assets/templates/dataset-filter/preview-page.tmpl
- assets/templates/dataset-filter/time.tmpl
- assets/templates/feedback.tmpl
- assets/templates/geography/area.tmpl
- assets/templates/geography/homepage.tmpl
- assets/templates/geography/list.tmpl
- assets/templates/main.tmpl
- assets/templates/partials/breadcrumb.tmpl
Release 1.58.0
- ✅ [Move breadcrumbs outside of <main>](https://trello.com/c/hbzSELVv/1631-move-breadcrumbs-outside-of-main)
Sense check
Nothing's there that shouldn't be
!me
> Release 1.58.0
